run:
  cargo run

# build for both native and riscv targets
build:
  cargo build --release
  cargo build --release --target=riscv32imac-unknown-none-elf --no-default-features --features target_vanadium_ledger

# build for native target
build-native:
  cargo build --release

# build for riscv target (Ledger Vanadium)
build-riscv:
  cargo build --release --target=riscv32imac-unknown-none-elf --no-default-features --features target_vanadium_ledger

